name: Tests for opam-sysinstall
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        operating-system: [ macos-latest, ubuntu-latest ]
        ocaml-version: [ '4.11.1' ]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Pinning Package
      run: opam pin add -n -y .
    - name: Packages
      run: opam depext -yt opam-sysinstall
    - name: Dependencies
      run: opam install -t -y . --deps-only
    - name: Building
      run: opam exec -- dune build
    - name: Installing
      run: opam exec -- dune install
    - name: Install location
      run: mkdir -p /home/runner/ocaml
    - name: Testing (dry run)
      run: opam exec -- opam sysinstall build --prefix=/home/runner/ocaml --versions=4.11.1,4.07.1 --dry-run
    - name: Testing
      run: opam exec -- opam sysinstall build --prefix=/home/runner/ocaml --versions=4.11.1,4.07.1
    - name: Inspecting
      run: |
        echo "let () = print_endline Sys.ocaml_version" > main.ml
        /home/runner/4.11.1/bin/ocamlopt main.ml -o eleven.out
        ./eleven.out
        /home/runner/4.7.1/bin/ocamlopt main.ml -o seven.out
        ./seven.out
